version: '3'
services:
  selenium:
    container_name: selenium-chrome
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: "2gb"
  selenium-app:
    container_name: selenium-app
    build: ./app
    volumes:
      - ./app:/opt/app
    tty: true
